port-code = "xxx"
port-code = ${?PORT_CODE}

days-to-look-back = 5
days-to-look-back = ${?DAYS_TO_LOOK_BACK}

include "org.apache.pekko.conf"
include "jdbc.conf"
include "aggregated-db.conf"

environment = "production"

options {
  job-name: ${?JOB_NAME}
  job-timeout-minutes: 60
  job-timeout-minutes: ${?JOB_TIMEOUT_MINUTES}
  dry-run: false
  dry-run: ${?DRY_RUN}
  dump-predictions-file-path: ${?DUMP_PREDICTIONS_FILE_PATH}
  training {
    days-of-data: 150
    days-of-data: ${?TRAINING_DAYS_OF_DATA}
  }
  gates-walk-time-file-path: ""
  gates-walk-time-file-path: ${?GATES_WALK_TIME_FILE_PATH}
  stands-walk-time-file-path: ""
  stands-walk-time-file-path: ${?STANDS_WALK_TIME_FILE_PATH}
}

aws {
  access-key-id = ${?AWS_ACCESS_KEY_ID}
  secret-access-key = ${?AWS_SECRET_ACCESS_KEY}
  s3 {
    bucket = ${?AWS_S3_BUCKET}
    path = ${?AWS_S3_PATH}
  }
}

aggregated-db {
  connectionPool = "HikariCP"
  driver = "org.postgresql.Driver"
  host = "localhost"
  host = ${?AGGDB_HOST}
  numThreads = 2
  numThreads = ${?AGGDB_THREADS}
  maxConnections = 2
  maxConnections = ${?AGGDB_MAX_CONNECTIONS}
  user = "drt"
  user = ${?AGGDB_USER}
  password = "drt"
  password = ${?AGGDB_PASSWORD}
  database = "aggregated"
  database = ${?AGGDB_DB}
  url = "jdbc:postgresql://"${aggregated-db.host}":5432/"${aggregated-db.database}"?user="${aggregated-db.user}"&password="${aggregated-db.password}"&ssl="${use-pg-ssl}"&sslmode="${use-pg-ssl-mode}""
}
